### ISSUE TITLE
Alternative configuration options

### ISSUE THREAD

**Issue by nicwortel** [leedavis81/drest#11]
All examples in the documentation seem to use annotations for configuring the mapping between entity and REST resource. Are there any alternative options, such as YAML / XML files, like when using Doctrine?

Something like this:

``` yaml
Acme\DemoBundle\Entity\User:
    routes:
        get_users:
            pattern:    /users
            verbs:      [GET]
            collection: true
        get_user:
            pattern:    /user/:id
            verbs:      [GET]
        update_user:
            pattern:    /user/:id
            verbs:      [PUT, PATCH]
            origin:     get_user
```

The reason for this is that I want to keep the persistance logic seperated from my entities. My entities shouldn't know how they are going to be saved.

Is it possible? If not, I'd like to propose this as a new feature.
